### ISSUE TITLE
Input field doesn't render correctly

### ISSUE THREAD

**Issue by BenParizek** [selvinortiz/craft.doxter#22]
I recently updated to the latest version of Craft and am now seeing my Doxter fields render HTML as plain text:
http://share.barrelstrength.co/0Z0D1a1s2D3I

Not sure what might have changed to change how that is being output.  In any case, I was able to get it displaying properly again by rendering the input field using the raw filter.

/templates/fields/doxter/input.html

FROM 
{{ field }}

TO:
{{ field | raw }}

I'm using Craft Pro 2.5.2759 and Doxter 1.1.0

**Comment by selvinortiz** [comment]
This was fixed in November, you should download the latest version, which is *1.1.1* and not reflected in the read me.

**Comment by BenParizek** [comment]
Alright, got it working.  Just to note, downloading v1.1.1 from the Releases tab (https://github.com/selvinortiz/craft.doxter/releases/tag/v1.1.1) does not fix this issue, however, downloading the latest zip on the master branch (also v1.1.1) does fix it.
